# Main workflow for testing and releasing

name: CI/CD

env:
  GOVERSION: "1.22.4"
  NAME: "fynemeta"
  PREFIX: ""

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}

    - name: Set prefix
      run: |
        VERSION=${{ github.ref_name }}
        echo "PREFIX=${{ env.NAME }}-${VERSION:1}" >> $GITHUB_ENV

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install zip gzip tar

    - name: Build linux
      run: GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=${{  github.ref_name }}" -o ./build/linux/ .

    - name: Package linux
      run: tar --directory=build/linux -czvf ${{ env.PREFIX }}-linux-amd64.tar.gz ${{ env.NAME }}

    - name: Build windows
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-X main.Version=${{  github.ref_name }}" -o ./build/windows/ .

    - name: Package windows
      run: zip -j ${{ env.PREFIX }}-windows-amd64.zip ./build/windows/${{ env.NAME }}.exe

    - name: Build darwin
      run: GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Version=${{  github.ref_name }}" -o ./build/darwin/ .

    - name: Package darwin
      run: zip -j ${{ env.PREFIX }}-darwin-amd64.zip ./build/darwin/${{ env.NAME }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        fail_on_unmatched_files: true
        files: |
          ${{ env.PREFIX }}-darwin-amd64.zip
          ${{ env.PREFIX }}-linux-amd64.tar.gz
          ${{ env.PREFIX }}-windows-amd64.zip
